name: prose-down
version: '0.0.0'
# synopsis:
# description:
# category:
author: tett23
maintainer: tett23@gmail.com
license: MIT
github: tett23/prose-down
homepage: https://github.com/tett23/prose-down
dependencies:
  - parsec >= 3.1
  - base >= 4.7 && < 5

library:
  source-dirs: src/
  ghc-options: []
  generated-exposed-modules: []
  exposed-modules: []
# executables:
#   stack:
#     main: Parser.hs
#     source-dirs: src/
