[package]
name = "parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
pest = { workspace = true }
pest_derive = { workspace = true }
serde = { workspace = true, features = ['rc'] }
serde_json = { workspace = true }

# lazy_static = { workspace = true }
[dev-dependencies]
insta = { version = "1.28.0", features = ["glob", "json"] }
