[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gokuraku"
path = "src/main.rs"
test = false
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
"prose_down" = { path = "../prose-down" }
